export enum DragonElement {
    Beauty = "beauty",
    Chaos = "chaos",
    Dark = "dark",
    Dream = "dream",
    Electric = "electric",
    Flame = "flame",
    Happy = "happy",
    Ice = "ice",
    Legend = "legend",
    Light = "light",
    Magic = "magic",
    Metal = "metal",
    Nature = "nature",
    Primal = "primal",
    Pure = "pure",
    Sea = "sea",
    Soul = "soul",
    Terra = "terra",
    War = "war",
    Wind = "wind",
}
